README.md
[노래추가] MC 스나이퍼
1. 몽환의 숲
2. BK LOVE
=> whatsong 노래추가

README.md
=> 음악 추가: And July

README.md
Sophia James - Life is gonna change
=> Life is gonna change 추가

README.md
=> 음악추가 오래된노래

README.md
=> 음악 추가 : 전부너였다

README.md
=> 노래 추가: 좋은 밤 좋은 꿈

README.md
=> love wins all 추가

README.md
3곡 추가 (장르: pop, jpop, game soundtrack)
=> 추천곡 3개 추가. (다양한 장르)

README.md
=> 음악 추가: 락앤롤데이

README.md
=> 음악 추가 :name : Beautiful Things -  Artist: Benson Boone

README.md
=> 음악 추가 : sunset

README.md
=> 음악 추가: 벌써일년

README.md
=> 음악 추가: 자작곡_김창운

README.md
=> 뉴진스의 하입보이 추가

README.md
=> 음악 추가(밤양갱)

README.md
=> 음악 추가 So Beautiful

README.md
=> 음악 추가  : 아름다워

README.md
=> 최유리 - 모닥불 추가

README.md
=> 노래 추가 : Time Bomb

README.md
=> 음악 추가 : 홀씨

README.md
=> 음악 추천 추가.Fall Out Boy

README.md
- Artist: 에릭남&웬디
- Genre: K-Pop
- [유투브 바로가기](https://music.youtube.com/watch?v=erErBFKPbMY&si=8iyNleohwtnCDllB)
=> 노래 추가 : Spring Love

README.md
(They Long To Be) Close To You
Carpenters
=> 노래 추천 추가: Close To You

README.md
=> 잔잔한 피아노 재즈 리스트

README.md
=> 추천 노래 추가: out of time

README.md
=> 음악 추가 : The Chicken

README.md
=> 노래 추가: 씨밤바

README.md
=> 노래추가 정인 - 장마

README.md
=> Lil Boo Thang 음악 추가

README.md
=> 노래 추가: Peacesign

README.md
=> Welcome to the Show 추가

README.md
=> 노래 추가 : boy for the weekend

README.md
제가 좋아하는 노래입니다.
노래가 좋아서 영화까지 찾아봤어요.
=> 노래추가 : falling slowly

README.md
=> 노래 추가 : 한숨

README.md
=> own my hero 추가

README.md
=> 노래추가 흰수염 고래

README.md
=> 노래 추가 : 첫사랑

README.md
=> 노래 추가 : 하루하루

README.md
=> 노래 추가: Catalina

README.md
=> 노래 추가 : Love

README.md
=> 노래 추가 - We are

README.md
=> 노래 추가: 덤디덤디

README.md
=> 노래 추가: 빠지기는 빠지더라

README.md
=> 노래 추가: The Ocean

README.md
=> 노래 추가: Noid

README.md
=> 음악 추가: gift

README.md
=> 음악 추가: Sweet Child O' Mine

README.md
=> 노래 추가: 青と夏

README.md
=> 164 - 노래 추가 : 별을 담은 시

README.md
AeroSmith의 I don't want to miss a thing 추가요~!
=> feat 노래 추가 I don't want to miss a thing

README.md
노래 추가 : World's Smallest Violin
=> 노래 추가 : World's Smallest Violin

README.md
---
name: 노래 추가 PR
assignees: ""
---
- 이슈 번호: # (연결된 이슈 번호를 입력해주세요)
- 추가한 노래:
- **노래 제목**: (여기에 노래 제목을 입력해주세요)
- **아티스트**: (여기에 아티스트 이름을 입력해주세요)
- **장르**: (여기에 장르를 입력해주세요)
- **유튜브 링크**: (있다면 유튜브 주소를 입력해주세요)
=> 음악 추가: 반딧불

README.md
---
name: 노래 추가 PR
assignees: ""
---
- 이슈 번호: # 243
- 추가한 노래:
- **노래 제목**: Eyes closed
- **아티스트**: Ed sheeran
- **장르**: pop
- **유튜브 링크**: https://www.youtube.com/watch?v=FUzc9qqBn4s
=> 노래 추가: Eyes closed

README.md
---
name: 노래 추가 PR
assignees: ""
---
- 이슈 번호: # (연결된 이슈 번호를 입력해주세요)
- 추가한 노래:
- **노래 제목**: (여기에 노래 제목을 입력해주세요)
- **아티스트**: (여기에 아티스트 이름을 입력해주세요)
- **장르**: (여기에 장르를 입력해주세요)
- **유튜브 링크**: (있다면 유튜브 주소를 입력해주세요)
=> 음악 추가: Paradise City

README.md
---
name: 노래 추가 PR
assignees: ""
---
- 이슈 번호: # 287
- 추가한 노래:
- **노래 제목**: 체념
- **아티스트**: 이영현
- **장르**: 발라드
- **유튜브 링크**: https://youtu.be/ARJ5bXkof30?si=6Dnb4TKDRzGFu-Zz
=> 음악 추가: 체념 - 이영현

README.md
---
name: 노래 추가 PR
assignees: ""
---
- 이슈 번호: # 293
- 추가한 노래:
- **노래 제목**: HAPPY
- **아티스트**: DAY6
- **장르**: POP PUNK
- **유튜브 링크**: https://youtu.be/sWXGbkM0tBI?si=gQRh9Sm-u22YEA4R
=> 음악 추가 : HAPPY

README.md
---
name: 노래 추가 PR
title: "[노래 추가] day 1 - HONNE"
assignees: ""
---
- 이슈 번호: #291
- 추가한 노래:
- **노래 제목**: day 1 
- **아티스트**: HONNE
- **장르**: POP
- **유튜브 링크**: [유튜브 바로가기](https://www.youtube.com/watch?v=QjrkrVmC-8M)
=> 음악 추가: day 1

README.md
---
name: 노래 추가 PR
assignees: ""
---
- 이슈 번호: # 289
- 추가한 노래:
- **노래 제목**: CUFF IT
- **아티스트**: Beyonce
- **장르**: Pop
- **유튜브 링크**: https://www.youtube.com/watch?v=yrtWLyp5gLI
=> 음악추가 : CUFF IT

README.md
---
name: 노래 추가 PR
assignees: ""
---
- 이슈 번호: #282 
- 추가한 노래:
- **노래 제목**: 2 soon
- **아티스트**: keshi
- **장르**: POP
- **유튜브 링크**: https://www.youtube.com/watch?v=LKZyp2cSAy4
=> 음악 추가: 2 soon
